#undef _PATH_CRACKLIB
#undef ADMIN_GRP
#undef CAPDIR
#undef DEBUG
#undef NO_DDP
#undef SERVERTEXT
#undef SHADOWPW
#undef TCPWRAP
#undef USE_CAP
#undef USE_CRACKLIB
#undef USE_FLOCK_LOCKS
#undef USE_PAM
