#!/bin/sh

set -x

rm -rf autom4te*.cache

LIBTOOLIZE=libtoolize
SYSNAME=`uname`
if [ "x$SYSNAME" = "xDarwin" ] ; then
  LIBTOOLIZE=glibtoolize
fi

# build it all.
aclocal -I macros $ACLOCAL_FLAGS || exit 1
autoheader || exit 1
$LIBTOOLIZE --force --copy
automake --include-deps --add-missing --foreign --copy || exit 1
autoconf || exit 1

# libevent
cd libevent
aclocal -I m4 && \
	autoheader && \
	$LIBTOOLIZE --force --copy && \
	autoconf && \
	automake --include-deps --add-missing --force-missing --copy || exit 1

# Let's not fall off the end...
exit 0
