#!/bin/sh

set -x

rm -rf autom4te*.cache

# build it all.
aclocal -I macros $ACLOCAL_FLAGS || exit 1
autoheader || exit 1
libtoolize --force --copy
automake --include-deps --add-missing --foreign --copy || exit 1
autoconf || exit 1

cd libevent && ./autogen.sh

# Let's not fall off the end...
exit 0
