services:
  netatalk:
    image: netatalk:latest
    network_mode: "host"
    cap_add:
      - NET_ADMIN
    volumes:
      - afpshare:/mnt/afpshare
      - afpbackup:/mnt/afpbackup
      - /var/run/dbus:/var/run/dbus
    environment:
      - AFP_USER=
      - AFP_PASS=
      - AFP_GROUP=afpusers
      - ATALKD_INTERFACE=
      - TZ=
volumes:
  afpshare:
  afpbackup:
