#!/bin/sh
#
# buildrpm
# $Id: buildrpm,v 1.2 2001-02-20 16:57:32 rufustfirefly Exp $
#
# automates the process of building the netatalk rpm

REDHAT_DIR=/usr/src/redhat
CVSNAME=netatalk

# clean out any object files
cd ../../
make clean

# tar up the archive
cd ../
tar -c -v -f -z ${REDHAT_DIR}/SOURCES/netatalk.tar.gz \
	--exclude="*/CVS" --exclude="*~" $CVSNAME

# build the rpm
rpm -ba ${REDHAT_DIR}/SPECS/netatalk.spec

