#!/bin/sh
#
# PROVIDE: macipgw
# REQUIRE: atalkd
#
# IP-over-AppleTalk

. /etc/rc.subr

name="macipgw"
rcvar=$name
command="/usr/pkg/bin/macipgw"
command_args="-z Ryuuu -n 192.168.1.254 192.168.3.0 255.255.255.0"

load_rc_config $name
run_rc_command "$1"

