.TH ATALKD 8 "17 Nov 1995" "netatalk 1.3"
.SH NAME
atalkd \- AppleTalk RTMP, NBP, ZIP, and AEP manager
.SH SYNOPSIS
.B :SBINDIR:/atalkd
[
.B -f
.I configfile
] [
.B -1
|
.B -2
]
.SH DESCRIPTION
.B atalkd
is responsible for all user level AppleTalk network management. This
includes routing, name registration and lookup, zone lookup, and the
AppleTalk Echo Protocol (similar to
.BR ping (8)).
.B atalkd
is typically started at boot time, out of
.B /etc/rc.
It first reads from its configuration file,
.BR :ETCDIR:/atalkd.conf .
If there is no configuration file,
.B atalkd
will attempt to configure all available interfaces and will create a
configuration file.  The file consists of a series of interfaces, one
per line.  Lines with
.RB ` # '
in the first column are ignored, as are blank lines.  The syntax is
.RS
.sp
.I interface
[
.B -seed
] [
.B -phase
.I number
] [
.B -net
.I net-range
] [
.B -addr
.I address
] [
.B -zone
.I zonename
] ...
.sp
.RE
Note that all field except the
.I interface
are optional.  The loopback interface is configured automatically.  If
.B -seed
is specified, all other fields must be present.  Also,
.B atalkd
will exit during bootstrapping, if a router disagrees with its seed
information.  If
.B -seed
is not given, all other information may be overriden during
auto-configuration.  If no
.B -phase
option is given, the default phase as given on the command line is used
(the default is 2).  If
.B -addr
is given and
.B -net
is not, a
.I net-range
of one is assumed.
.LP
The first
.B -zone
directive for each interface is the ``default'' zone.  Under Phase 1, there
is only one zone.  Under Phase 2, all routers on the network are
configured with the default zone and must agree.
.B atalkd
maps ``*'' to the default zone of the first interface.  Note:  The
default zone for a machine is determined by the configuration of the
local routers; to appear in a non-default zone, each service, e.g.
.BR afpd ,
must individually specify the desired zone.  See also
.BR nbp_name (3).
.SH ROUTING
If you are connecting a netatalk router to an existing AppleTalk
internet, you should first contact your local network administrators to
obtain appropriate network addresses.
.LP
.B atalkd
can provide routing between interfaces by configuring multiple
interfaces.  Each interface must be assigned a unique
.I net-range
between 1 and 65279 (0 and 65535 are illegal, and addresses between
65280 and 65534 are reserved for startup).  It is best to choose the
smallest useful
.IR net-range ,
i.e. if you have three machines on an Ethernet, don't chose a
.I net-range
of 1000-2000.  Each
.I net-range
may have an arbitrary list of zones associated with it.
.SH EXAMPLE
Below is an example configuration file for a sun4/40.  The machine has
two interfaces, ``le0'' and ``le1''.  The ``le0'' interface is
configured automatically from other routers on the network.  The
machine is the only router for the ``le1'' interface.
.sp
.RS
.nf
le0
le1 -seed -net 9461-9471 -zone netatalk -zone Argus
.fi
.RE
.sp
.B atalkd
automatically acts as a router if there is more than one interface.
.SH FILES
.TP 30
.B :ETCDIR:/atalkd.conf
configuration file
.SH BUGS
On some systems, atalkd can not be restarted.
