'\" t
.\"     Title: timelord
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.75.2 <http://docbook.sf.net/>
.\"      Date: 27 Jun 2001
.\"    Manual: The Netatalk Project
.\"    Source: Netatalk 2.2
.\"  Language: English
.\"
.TH "TIMELORD" "8" "27 Jun 2001" "Netatalk 2.2" "The Netatalk Project"
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
timelord \- Macintosh time server daemon
.SH "SYNOPSIS"
.SH "SYNTAX"
.PP
timelord [\-d] [\-n
\fIfilename\fR]
.SH "DESCRIPTION"
.PP
\fBtimelord\fR
is a simple time server for Macintosh computers that use the
\fBtardis\fR
client\&.
.SH "OPTIONS"
.PP
\fB\-d\fR
.RS 4
Debug mode, i\&.e\&. don\'t disassociate from controlling TTY\&.
.RE
.PP
\fB\-n\fR \fInbpname\fR
.RS 4
Register this server as
\fInbpname\fR\&. This defaults to the hostname\&.
.RE
