.TH timelord 8 "27 Jun 2001" 2.0.0 Netatalk 
.SH NAME
timelord \- Macintosh time server daemon
.SH SYNOPSIS
.SH SYNTAX
timelord [\-d] [\-n \fIfilename\fR]
.SH DESCRIPTION
\fItimelord\fR is a simple time server for
Macintosh computers that use the \fItardis\fR
client.
.SH OPTIONS
.TP 
\fB\-d\fR
Debug mode, i.e. don't disassociate from controlling
TTY.
.TP 
\fB\-n\fR \fInbpname\fR
Register this server as \fInbpname\fR. This defaults to the hostname.

