'\" t
.\"     Title: achfile
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.74.3 <http://docbook.sf.net/>
.\"      Date: 26 Feb 1998
.\"    Manual: Netatalk 2.1
.\"    Source: Netatalk 2.1
.\"  Language: English
.\"
.TH "ACHFILE" "1" "26 Feb 1998" "Netatalk 2.1" "Netatalk 2.1"
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
achfile \- change type and/or creator of Apple Macintosh files (netatalk format)
.SH "SYNOPSIS"
.HP \w'\fBachfile\fR\fB\fR\ 'u
\fBachfile\fR\fB\fR [\-t\ \fItype\fR] [\-c\ \fIcreator\fR] \fIfile\fR...
.SH "DESCRIPTION"
.PP
\fBachfile\fR
changes the Macintosh type and/or creator of the
\fIfile\fR
arguments which have a corresponding \&.AppleDouble file\&.
.SH "OPTIONS"
.PP
\fB\-t\fR
\fItype\fR
change the type\&.
.PP
\fB\-c\fR
\fIcreator\fR
change the creator\&.
.SH "DIAGNOSTICS"
.PP
returns exit status 0 if all files changed successfully
.SH "SEE ALSO"
.PP
\fBafile\fR(1),
\fBafpd\fR(8)
