'\" t
.\"     Title: afile
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.74.3 <http://docbook.sf.net/>
.\"      Date: 26 Feb 1998
.\"    Manual: Netatalk 2.1
.\"    Source: Netatalk 2.1
.\"  Language: English
.\"
.TH "AFILE" "1" "26 Feb 1998" "Netatalk 2.1" "Netatalk 2.1"
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
afile \- display type and creator of Apple Macintosh files (netatalk format)
.SH "SYNOPSIS"
.HP \w'\fBafile\fR\fB\fR\ 'u
\fBafile\fR\fB\fR [\-a] \fIfile\fR...
.br

.SH "DESCRIPTION"
.PP
\fBafile\fR
displays the name and Macintosh type and creator of the
\fIfile\fR
arguments\&. Tests whether the file is an AppleDouble header, in which case it checks the corresponding data fork exists, or assumes it is a data fork in which case it looks for the corresponding AppleDouble to find the type/creator information\&.
.PP
\fBafile\fR
does not look at any of the extension mapping files such as AppleVolumes\&.system\&.
.SH "OPTIONS"
.PP
\fB\-a\fR
.RS 4
Include directories and data files of unknown type (i\&.e\&. without corresponding AppleDouble) in output\&.
.RE
.SH "DIAGNOSTICS"
.PP
returns exit status 0 if all files have a corresponding valid \&.AppleDouble header or data fork, or 99 for bad command line options\&. Otherwise it returns the following error code relating to the last invalid file\&.
.PP
1 file doesn\'t exist
.PP
2 file is unreadable
.PP
3 file is directory
.PP
4 file is AppleDouble without data fork
.PP
5 file is AppleDouble with unreadable data fork
.PP
6 file is data fork without AppleDouble
.PP
7 file is data fork with unreadable AppleDouble
.PP
8 file is data fork with short AppleDouble
.PP
9 bad magic in AppleDouble
.SH "SEE ALSO"
.PP
\fBachfile\fR(1),
\fBafpd\fR(8)
