.TH APPLE_RM 1 "16 Oct 2001" "Netatalk 1.5"
.SH NAME
apple_rm \- Do an apple remove, remove the resource fork as well

.SH SYNOPSIS
.BR apple_rm
\fIFILE\fR...

.SH DESCRIPTION
.BR apple_rm
is a perl script that removes FILE(s) as well as the .AppleDouble
resource fork file(s) that corresponds to FILE(s). 
.BR apple_rm
does not delete directories.

.SH EXAMPLES

.BR apple_rm
test.text 

.BR apple_rm
test.text testing.text

.SH REPORTING BUGS
Report bugs to the Netatalk-devel list <netatalk-devel@lists.sourceforge.net>.

.SH SEE ALSO
.BR apple_cp (1),
.BR apple_mv (1).

