.TH APPLE_MV 1 "16 Oct 2001" "Netatalk 1.5"
.SH NAME
apple_mv \- Do an apple move, moving the resource fork as well
.SH SYNOPSIS
.BR apple_mv
\fISOURCE DEST\fR
.br
.BR apple_mv
\fISOURCE\fR... \fIDIRECTORY\fR

.SH DESCRIPTION
.BR apple_mv
is a perl script to move SOURCE to DEST or multiple SOURCE(s) to
DIRECTORY. It also moves the resource forks to the .AppleDouble
directory for DEST or DIRECTORY. If the .AppleDouble directory doesn't
exist for DEST or DIRECTORY it will create it.

.SH EXAMPLES

.BR apple_mv
test.text /target/directory/

.BR apple_mv
test.text /target/directory/test2.text

.BR apple_mv
test.text testing.text /target/directory/

.SH REPORTING BUGS
Report bugs to the Netatalk-devel list <netatalk-devel@lists.sourceforge.net>.

.SH SEE ALSO
.BR apple_cp (1),
.BR apple_rm (1).
