.TH getzones 1 "17 Dec 1991" 2.0.0 Netatalk 
.SH NAME
getzones \- list AppleTalk zone names
.SH SYNOPSIS
\fBgetzones\fR [\-m | \-l] [\fBaddress\fR]
.SH DESCRIPTION
\fIGetzones\fR is used to obtain a list of
AppleTalk zone names using the Zone Information Protocol (ZIP). It sends a
GetZoneList request to an AppleTalk router. By default, it sends the
request to the locally running \fBatalkd\fR(8).
.SH OPTIONS
.TP 
\fB\-m\fR
List the name of the local zone only; this is accomplished by
sending a ZIP GetMyZone request.
.TP 
\fB\-l\fR
List the local zones; this is accomplished by sending a
GetLocalZones request.
.TP 
\fIaddress\fR
Contact the AppleTalk router at \fIaddress.\fR
\fIaddress\fR is parsed by
\fBatalk_aton\fR(3).
.SH "SEE ALSO"
\fBatalk_aton\fR(3),
\fBatalkd\fR(8).

