'\" t
.\"     Title: getzones
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.75.2 <http://docbook.sf.net/>
.\"      Date: 17 Dec 1991
.\"    Manual: Netatalk 2.2
.\"    Source: Netatalk 2.2
.\"  Language: English
.\"
.TH "GETZONES" "1" "17 Dec 1991" "Netatalk 2.2" "Netatalk 2.2"
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
getzones \- list AppleTalk zone names
.SH "SYNOPSIS"
.HP \w'\fBgetzones\fR\fB\fR\ 'u
\fBgetzones\fR\fB\fR [\-m | \-l] [\fIaddress\fR]
.SH "DESCRIPTION"
.PP
\fBGetzones\fR
is used to obtain a list of AppleTalk zone names using the Zone Information Protocol (ZIP)\&. It sends a GetZoneList request to an AppleTalk router\&. By default, it sends the request to the locally running
\fBatalkd\fR(8)\&.
.SH "OPTIONS"
.PP
\fB\-m\fR
.RS 4
List the name of the local zone only; this is accomplished by sending a ZIP GetMyZone request\&.
.RE
.PP
\fB\-l\fR
.RS 4
List the local zones; this is accomplished by sending a GetLocalZones request\&.
.RE
.PP
\fIaddress\fR
.RS 4
Contact the AppleTalk router at
\fIaddress\&.\fR
\fIaddress\fR
is parsed by
\fBatalk_aton\fR(3)\&.
.RE
.SH "SEE ALSO"
.PP
\fBatalk_aton\fR(3),
\fBatalkd\fR(8)\&.
