.TH nbp 1 "24 June 2004" 2.0.0 Netatalk 
.SH NAME
nbplkup, nbprgstr, nbpunrgstr \- access NBP database
.SH SYNOPSIS
\fBnbplkup \fR[\-r \fBmaxresponses\fR] [\-A \fBaddress\fR] [\-m \fBmaccodepage\fR] \fBnbpname\fR 
.PP
\fBnbprgstr \fR[\-A \fBaddress\fR] [\-p \fBport\fR] [\-m \fBmaccodepage\fR] \fBnbpname\fR 
.PP
\fBnbpunrgstr \fR[\-A \fBaddress\fR] [\-m \fBmaccodepage\fR] \fBnbpname\fR 
.SH DESCRIPTION
nbprgstr registers \fInbpname\fR
with \fBatalkd\fR(8),
at the given \fIport\fR. nbpunrgstr
informs \fIatalkd\fR that
\fInbpname\fR is no longer to be advertised.
.PP
nbplkup displays up to
\fImaxresponses\fR (default 1000) entities registered
on the AppleTalk internet. \fInbpname\fR
is parsed by \fBnbp_name\fR(3).
An `\fI=\fR' for the \fIobject\fR
or \fItype\fR matches anything, and an `\fI*\fR' for \fIzone\fR means
the local zone. The default values are taken from the \fINBPLKUP\fR
environment variable, parsed as an \fInbpname\fR.
.SH "ENVIRONMENT VARIABLES"
.TP 
NBPLKUP
default nbpname for nbplkup
.TP 
ATALK_MAC_CHARSET
the codepage used by the clients on the Appletalk network
.TP 
ATALK_UNIX_CHARSET
the codepage used to display extended characters on this
shell.
.SH EXAMPLE
Find all devices of type \fILaserWriter\fR
in the local zone.
.PP
.nf
example% \fBnbplkup :LaserWriter\fR
               Petoskey:LaserWriter        7942.129:218
             Gloucester:LaserWriter        8200.188:186
                 Rahway:LaserWriter        7942.2:138
             517 Center:LaserWriter        7942.2:132
                  ionia:LaserWriter        7942.2:136
     Evil DEC from Hell:LaserWriter        7942.2:130
              Hamtramck:LaserWriter        7942.2:134
         Iron Mountain :LaserWriter        7942.128:250
example%
.fi
.SH "SEE ALSO"
\fBnbp_name\fR(3),
\fBatalkd\fR(8).

