'\" t
.\"     Title: nbp
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.75.2 <http://docbook.sf.net/>
.\"      Date: 24 June 2004
.\"    Manual: Netatalk 2.2
.\"    Source: Netatalk 2.2
.\"  Language: English
.\"
.TH "NBP" "1" "24 June 2004" "Netatalk 2.2" "Netatalk 2.2"
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
nbp, nbplkup, nbprgstr, nbpunrgstr \- access NBP database
.SH "SYNOPSIS"
.HP \w'\fBnbplkup\fR\fB\fR\fB\fR\fB\ \fR\ 'u
\fBnbplkup\fR\fB\fR\fB\fR\fB \fR [\-r\ \fImaxresponses\fR] [\-A\ \fIaddress\fR] [\-m\ \fImaccodepage\fR] \fInbpname\fR
.HP \w'\fBnbprgstr\fR\fB\fR\fB\ \fR\ 'u
\fBnbprgstr\fR\fB\fR\fB \fR [\-A\ \fIaddress\fR] [\-p\ \fIport\fR] [\-m\ \fImaccodepage\fR] \fInbpname\fR
.HP \w'\fBnbpunrgstr\fR\fB\fR\fB\ \fR\ 'u
\fBnbpunrgstr\fR\fB\fR\fB \fR [\-A\ \fIaddress\fR] [\-m\ \fImaccodepage\fR] \fInbpname\fR
.SH "DESCRIPTION"
.PP
\fBnbprgstr\fR
registers
\fInbpname\fR
with
\fBatalkd\fR(8), at the given
\fIport\fR\&.
\fBnbpunrgstr\fR
informs
\fBatalkd\fR
that
\fInbpname\fR
is no longer to be advertised\&.
.PP
\fBnbplkup\fR
displays up to
\fImaxresponses\fR
(default 1000) entities registered on the AppleTalk internet\&.
\fI\fInbpname\fR\fR
is parsed by
\fBnbp_name\fR(3)\&. An `\fB=\fR\' for the
\fIobject\fR
or
\fItype\fR
matches anything, and an `\fB*\fR\' for
\fIzone\fR
means the local zone\&. The default values are taken from the
\fBNBPLKUP\fR
environment variable, parsed as an
\fInbpname\fR\&.
.SH "ENVIRONMENT VARIABLES"
.PP
NBPLKUP
.RS 4
default nbpname for nbplkup
.RE
.PP
ATALK_MAC_CHARSET
.RS 4
the codepage used by the clients on the Appletalk network
.RE
.PP
ATALK_UNIX_CHARSET
.RS 4
the codepage used to display extended characters on this shell\&.
.RE
.SH "EXAMPLE"
.PP
Find all devices of type
\fBLaserWriter\fR
in the local zone\&.
.sp
.if n \{\
.RS 4
.\}
.nf
example% \fBnbplkup :LaserWriter\fR
               Petoskey:LaserWriter        7942\&.129:218
             Gloucester:LaserWriter        8200\&.188:186
                 Rahway:LaserWriter        7942\&.2:138
             517 Center:LaserWriter        7942\&.2:132
                  ionia:LaserWriter        7942\&.2:136
     Evil DEC from Hell:LaserWriter        7942\&.2:130
              Hamtramck:LaserWriter        7942\&.2:134
         Iron Mountain :LaserWriter        7942\&.128:250
example%
.fi
.if n \{\
.RE
.\}
.SH "SEE ALSO"
.PP
\fBnbp_name\fR(3),
\fBatalkd\fR(8)\&.
