.TH netatalk\-config 1 "09 June 2001" 2.0.0 Netatalk 
.SH NAME
netatalk\-config \- script to get information about the installed version of netatalk
.SH SYNOPSIS
\fBnetatalk\-config\fR [ \-\-prefix [\fB=DIR\fR]] [ \-\-exec_prefix [\fB=DIR\fR]] [\-\-help] [\-\-version] [\-\-libs] [\-\-libs\-dirs] [\-\-libs\-names] [\-\-cflags] [\-\-macros]
.SH DESCRIPTION
netatalk\-config is a tool that is used to
determine the compiler and linker flags that should be used
to compile and link programs that use the \fInetatalk\fR
run\-time libraries.
.SH OPTIONS
netatalk\-config accepts the following options:
.TP 
\fB\-\-help\fR
Print a short help for this command and exit.
.TP 
\fB\-\-version\fR
Print the currently installed version of \fInetatalk\fR
on the standard output.
.TP 
\fB\-\-libs\fR
Print the linker flags that are necessary to link against the
\fInetatalk\fR run\-time libraries.
.TP 
\fB\-\-libs\-dirs\fR
Print only the \-l/\-R part of \-\-libs.
.TP 
\fB\-\-libs\-names\fR
Print only the \-l part of \-\-libs.
.TP 
\fB\-\-cflags\fR
Print the compiler flags that are necessary to compile a
program linked against the \fInetatalk\fR
run\-time libraries.
.TP 
\fB\-\-macros\fR
Print the \fInetatalk\fR m4
directory.
.TP 
\fB\-\-prefix=PREFIX\fR
If specified, use PREFIX instead of the installation prefix
that \fInetatalk\fR was built with when
computing the output for the \-\-cflags and \-\-libs options. This
option is also used for the exec prefix if \-\-exec\-prefix was not
specified. This option must be specified before any \-\-libs or
\-\-cflags options.
.TP 
\fB\-\-exec\\_prefix=PREFIX\fR
If specified, use PREFIX instead of the installation exec
prefix that \fInetatalk\fR was built with
when computing the output for the \-\-cflags and \-\-libs options. This
option must be specified before any \-\-libs or \-\-cflags options.
.SH COPYRIGHT
Copyright \(co 1998 Owen Taylor
.PP
Permission to use, copy, modify, and distribute this software and
its documentation for any purpose and without fee is hereby granted,
provided that the above copyright notice appear in all copies and that
both that copyright notice and this permission notice appear in supporting
documentation.
.PP
Man page adapted for netatalk\-config by Sebastian
Rittau in 2001.

