'\" t
.\"     Title: pap
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.75.2 <http://docbook.sf.net/>
.\"      Date: 6 May 2002
.\"    Manual: Netatalk 2.2
.\"    Source: Netatalk 2.2
.\"  Language: English
.\"
.TH "PAP" "1" "6 May 2002" "Netatalk 2.2" "Netatalk 2.2"
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
pap \- client interface to remote printers using Printer Access Protocol
.SH "SYNOPSIS"
.HP \w'\fBpap\fR\fB\fR\ 'u
\fBpap\fR\fB\fR [\-A\ \fIaddress\fR] [\-c] [\-d] [\-e] [\-E] [\-p\ \fInbpname\fR] [\-s\ \fIstatusfile\fR] [\-w] [\-W] [\fIFILES\fR]
.SH "DESCRIPTION"
.PP
\fBpap\fR
is used to connect and send files to an AppleTalk connected printer using the Apple Printer Access Protocol (PAP)\&. When
\fBpap\fR
starts execution, it tries to open a session with the printer using PAP, and then downloads the
\fIfiles\fR
to the printer\&.
.PP
If no
\fIfiles\fR
are given on the command line,
\fBpap\fR
begins reading from standard input\&.
.PP
If no printer is specified on the command line,
\fBpap\fR
looks for a file called
\fB\&.paprc\fR
in the current working directory and reads it to obtain the
\fInbpname\fR
of a printer\&. Blank lines and lines that begin with a `\fB#\fR\' are ignored\&.
\fItype\fR
and
\fIzone\fR
default to
\fBLaserWriter\fR
and the zone of the local host, respectively\&.
.PP
Note that
\fBpap\fR
is designed to be useful as a communication filter for sending
\fBlpd\fR(8)
spooled print jobs to AppleTalk connected printers\&. See
\fBpsf\fR(8)
for hints on how to use it this way\&.
.SH "OPTIONS"
.PP
\fB\-A \fR\fIaddress\fR
.RS 4
Connect to the printer with Appletalk address
\fIaddress\fR
and do not consult the
\fB\&.paprc\fR
file to find a printer name\&. See
\fBatalk_aton\fR(3)
for the syntax of
\fIaddress\fR\&.
.RE
.PP
\fB\-c\fR
.RS 4
Take cuts\&. The PAP protocol specified a simple queuing procedure, such that the clients tell the printer how long they have been waiting to print\&. This option causes
\fBpap\fR
to lie about how long it has been waiting\&.
.RE
.PP
\fB\-d\fR
.RS 4
Enable debug output\&.
.RE
.PP
\fB\-e\fR
.RS 4
Send any message from the printer to stderr instead of stdout\&.
\fBpsf\fR(8)
invokes
\fBpap\fR
with this option\&.
.RE
.PP
\fB\-E\fR
.RS 4
Don\'t wait for EOF from the printer\&. This option is useful for printers which don\'t implement PAP correctly\&. In a correct implementation, the client side should wait for the printer to return EOF before closing the connection\&. Some clients don\'t wait, and hence some printers have related bugs in their implementation\&.
.RE
.PP
\fB\-p\fR \fInbpname\fR
.RS 4
Connect to the printer named
\fInbpname\fR
and do not consult the
\fB\&.paprc\fR
file to find a printer name\&. See
\fBnbp_name\fR(3)
for the syntax of
\fInbpname\fR\&.
.RE
.PP
\fB\-s\fR \fIstatusfile\fR
.RS 4
Update the file called
\fIstatusfile\fR
to contain the most recent status message from the printer\&.
\fBpap\fR
gets the status from the printer when it is waiting for the printer to process input\&. The
\fIstatusfile\fR
will contain a single line terminated with a newline\&. This is useful when
\fBpap\fR
is invoked by
\fBpsf\fR(8)
within
\fBlpd\fR\'s spool directory\&.
.RE
.PP
\fB\-w\fR
.RS 4
Wait for the printer status to contain the word "waiting" before sending the job\&. This is to defeat printer\-side spool available on HP IV and V printers\&.
.RE
.PP
\fB\-W\fR
.RS 4
Wait for the printer status to contain the word "idle" before sending the job\&. This is to defeat printer\-side spool available on HP IV and V printers\&.
.RE
.SH "FILES"
.PP
\fB\&.paprc\fR
.RS 4
file read to obtain printer name if not specified on command line
.RE
.SH "SEE ALSO"
.PP
\fBnbp_name\fR(3),
\fBatalk_aton\fR(3),
\fBlpd\fR(8),
\fBpsf\fR(8)\&.
