.TH psorder 1 "17 Dec 1991" 2.0.0 Netatalk 
.SH NAME
psorder \- PostScript pageorder filter
.SH SYNOPSIS
\fBpsorder\fR [\-duf] \fBsourcefile\fR 
.SH DESCRIPTION
psorder is a filter that re\-orders the pages of a
PostScript document. The result is written to the standard output. By
default, documents are processed into ascending order (the lowest numbered
page is printed first). Some PostScript documents specify that the order
of their pages should never be changed; the default action of
psorder is to follow this specification.
.PP
If no source file is given, or if \fIsourcefile\fR
is `\fI\-\fR', psorder
reads from the standard input file.
.SH OPTIONS
.TP 
\fB\-d\fR
Re\-order the pages of the document in downward or descending
order. This is typically used to change the order of a document to
be printed by a printer that stacks pages face\-up, such as an Apple
LaserWriter or LaserWriter Plus.
.TP 
\fB\-u\fR
Specifies forward order, and is the default. It is used to try
and ensure the correct ordering when a document will be printed by a
printer that stacks the pages face\-down.
.TP 
\fB\-f\fR
Force psorder to re\-order the pages, even
if the document claims that its page order is not to be trifled
with. This option should only be used experimentally, as it may
cause documents to print incorrectly.
.SH "SEE ALSO"
\fBpsf\fR(8),
\fBlpr\fR(1).

