.TH timeout 1 "19 Jul 2001" 2.0.0 Netatalk 
.SH NAME
timeout \- Send a signal to a program after a certain time
.SH SYNTAX
timeout [\-s \fIsignal\fR] \fIseconds\fR \fIprogram\fR [\fIargs\fR]
.SH DESCRIPTION
\fItimeout\fR executes a \fIprogram\fR (with arguments \fIargs\fR)
and sends a \fIsignal\fR to it after a certain
amount of \fIseconds\fR.
.SH OPTIONS
.TP 
\fB\-s\fR \fIsignal\fR
Signal to send to the spawned process. This can be a numerical
or symbolic ID. This defaults to \fBTERM\fR.
.SH EXAMPLES
.TP 
timeout 10 pap foo.ps
Execute "pap foo.ps" and send a SIGTERM
if \fIpap\fR doesn't return after 10
seconds.
.TP 
timeout \-s HUP 60 sh
Spawn a shell and send a hangup signal after one minute.
.TP 
timeout \-s 9 10 evilprog
Execute a program and \fIKILL\fR it
if it doesn't quit after 10 seconds.

