name: Build Containers
on:
  workflow_run:
    workflows: [Tests]
    types:
      - completed

permissions: read-all
env:
    REGISTRY: ghcr.io
    REPO: ${{ github.repository }}

jobs:
    build-container:
        name: Build production container
        runs-on: ubuntu-latest
        timeout-minutes: 5
        permissions:
            contents: read
            packages: write
        steps:
            - name: Checkout repo
              uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
            - name: Create image name
              run: |
                echo "IMAGE_NAME=${REPO,,}" >> ${GITHUB_ENV}
            - name: Login to container registry
              uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772
              with:
                registry: ${{ env.REGISTRY }}
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}
            - name: Extract metadata
              id: metadata
              uses: docker/metadata-action@902fa8ec7d6ecbf8d84d538b9b233a880e428804
              with:
                images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
                tags: |
                  type=ref,event=branch
                  type=ref,event=tag
                  type=raw,value=latest
                  type=raw,value=${{ github.sha }}
            - name: Build and push container image
              uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83
              with:
                context: .
                file: Dockerfile
                push: true
                labels: ${{ steps.metadata.outputs.labels }}
                tags: ${{ steps.metadata.outputs.tags }}


    build-container-testsuite:
        name: Build Alpine testsuite container
        runs-on: ubuntu-latest
        timeout-minutes: 5
        permissions:
            contents: read
            packages: write
        steps:
            - name: Checkout repo
              uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
            - name: Create image name
              run: |
                echo "IMAGE_NAME=${REPO,,}-testsuite" >> ${GITHUB_ENV}
            - name: Login to container registry
              uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772
              with:
                registry: ${{ env.REGISTRY }}
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}
            - name: Extract metadata
              id: metadata
              uses: docker/metadata-action@902fa8ec7d6ecbf8d84d538b9b233a880e428804
              with:
                images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
                tags: |
                  type=ref,event=branch
                  type=ref,event=tag
                  type=raw,value=latest
                  type=raw,value=${{ github.sha }}
            - name: Build and push container image
              uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83
              with:
                context: .
                file: testsuite_alp.Dockerfile
                push: true
                labels: ${{ steps.metadata.outputs.labels }}
                tags: ${{ steps.metadata.outputs.tags }}


    build-container-webmin:
        name: Build Netatalk Webmin Module container
        runs-on: ubuntu-latest
        timeout-minutes: 5
        permissions:
            contents: read
            packages: write
        steps:
            - name: Checkout repo
              uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
            - name: Create image name
              run: |
                echo "IMAGE_NAME=${REPO,,}-webmin" >> ${GITHUB_ENV}
            - name: Login to container registry
              uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772
              with:
                registry: ${{ env.REGISTRY }}
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}
            - name: Extract metadata
              id: metadata
              uses: docker/metadata-action@902fa8ec7d6ecbf8d84d538b9b233a880e428804
              with:
                images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
                tags: |
                  type=ref,event=branch
                  type=ref,event=tag
                  type=raw,value=latest
                  type=raw,value=${{ github.sha }}
            - name: Build and push container image
              uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83
              with:
                context: .
                file: webmin_module.Dockerfile
                push: true
                labels: ${{ steps.metadata.outputs.labels }}
                tags: ${{ steps.metadata.outputs.tags }}


    build-container-testsuite-debian:
        name: Build Debian testsuite container
        runs-on: ubuntu-latest
        timeout-minutes: 5
        permissions:
            contents: read
            packages: write
        steps:
            - name: Checkout repo
              uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
            - name: Create image name
              run: |
                echo "IMAGE_NAME=${REPO,,}-testsuite-debian" >> ${GITHUB_ENV}
            - name: Login to container registry
              uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772
              with:
                registry: ${{ env.REGISTRY }}
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}
            - name: Extract metadata
              id: metadata
              uses: docker/metadata-action@902fa8ec7d6ecbf8d84d538b9b233a880e428804
              with:
                images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
                tags: |
                  type=ref,event=branch
                  type=ref,event=tag
                  type=raw,value=latest
                  type=raw,value=${{ github.sha }}
            - name: Build and push container image
              uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83
              with:
                context: .
                file: testsuite_deb.Dockerfile
                push: true
                labels: ${{ steps.metadata.outputs.labels }}
                tags: ${{ steps.metadata.outputs.tags }}
