name: Checks
on:
  push:
    branches:
      - dgsga-meson-builds
    paths-ignore:
      - "CONTRIBUTORS"
      - "NEWS"
      - "README.md"
  pull_request:
    branches:
      - main
      - branch-*
    types:
      - opened
      - synchronize
      - reopened
    paths-ignore:
      - "CONTRIBUTORS"
      - "NEWS"
      - "README.md"

env:
  APT_PACKAGES: |
    autoconf \
    automake \
    meson \
    ninja-build \
    docbook-xsl \
    libacl1-dev \
    libavahi-client-dev \
    libcrack2-dev \
    libdb-dev \
    libdbus-1-dev \
    libdbus-glib-1-dev \
    libevent-dev \
    libgcrypt-dev \
    libglib2.0-dev \
    libkrb5-dev \
    libldap2-dev \
    libmysqlclient-dev \
    libpam0g-dev \
    libssl-dev \
    libtalloc-dev \
    libtool \
    libtool-bin \
    libtracker-sparql-3.0-dev \
    libwrap0-dev \
    systemtap-sdt-dev \
    tcpd \
    tracker \
    xsltproc

jobs:
  build-ubuntu:
    name: Ubuntu
    runs-on: ubuntu-22.04
    container:
      image: ubuntu:23.10
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          apt-get update
          apt-get install --assume-yes --no-install-recommends \
            gcc \
            meson \
            ninja-build \
            default-libmysqlclient-dev \
            libacl1-dev \
            libavahi-client-dev \
            libcrack2-dev \
            libdb-dev \
            libdbus-1-dev \
            libdbus-glib-1-dev \
            libevent-dev \
            libgcrypt-dev \
            libglib2.0-dev \
            libkrb5-dev \
            libldap2-dev \
            libltdl-dev \
            libpam0g-dev \
            libssl-dev \
            libtalloc-dev \
            libtracker-sparql-3.0-dev \
            libwrap0-dev \
            systemtap-sdt-dev \
            tcpd \
            tracker
      - name: Configure
        run: |
          meson setup build \
            -Dwith-tracker-pkgconfig-version=3.0 \
            -Dbuild-tests=true
      - name: Build
        run: ninja -C build
      - name: Run tests
        run: cd build && meson test

  build-debian:
    name: Debian
    runs-on: ubuntu-22.04
    container:
      image: debian:trixie
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          apt-get update
          apt-get install --assume-yes --no-install-recommends \
            gcc \
            meson \
            ninja-build \
            default-libmysqlclient-dev \
            libacl1-dev \
            libavahi-client-dev \
            libcrack2-dev \
            libdb-dev \
            libdbus-1-dev \
            libdbus-glib-1-dev \
            libevent-dev \
            libgcrypt-dev \
            libglib2.0-dev \
            libkrb5-dev \
            libldap2-dev \
            libltdl-dev \
            libpam0g-dev \
            libssl-dev \
            libtalloc-dev \
            libtracker-sparql-3.0-dev \
            libwrap0-dev \
            systemtap-sdt-dev \
            tcpd \
            tracker
      - name: Configure
        run: |
          meson setup build \
            -Dwith-tracker-pkgconfig-version=3.0 \
            -Dbuild-tests=true
      - name: Build
        run: ninja -C build
      - name: Run tests
        run: cd build && meson test

  build-fedora:
    name: Fedora
    runs-on: ubuntu-22.04
    container:
      image: fedora:41
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          dnf -y install \
            meson \
            ninja-build \
            avahi-devel \
            cracklib-devel \
            dbus-devel \
            dbus-glib-devel \
            gcc \
            glib2-devel \
            krb5-devel \
            libacl-devel \
            libdb-devel \
            libgcrypt-devel \
            libtalloc-devel \
            openldap-devel \
            openssl-devel \
            pam-devel \
            perl \
            systemtap-sdt-devel \
            tracker-devel
      - name: Configure
        run: |
          meson setup build \
            -Dwith-tracker-pkgconfig-version=3.0 \
            -Dbuild-tests=true
      - name: Build
        run: ninja -C build
      - name: Run tests
        run: cd build && meson test

  build-macos:
    name: macOS
    runs-on: macos-13
    env:
      HOMEBREW_NO_INSTALL_CLEANUP: 1
      HOMEBREW_NO_AUTO_UPDATE: 1
      HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK: 1
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: brew install automake libressl mysql talloc krb5 berkeley-db meson
      - name: Configure
        run: |
          meson setup build \
            -Dwith-bdb=/usr/local/opt/berkeley-db \
            -Dwith-ssl-dir=/usr/local/opt/libressl \
            -Dbuild-tests=false
      - name: Build
        run: ninja -C build
      - name: Run tests
        run: cd build && meson test

  build-omnios:
    name: "OmniOS"
    runs-on: ubuntu-22.04
    permissions:
      contents: read
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v4
      - name: "Build on VM"
        uses: vmactions/omnios-vm@v1.0.1
        with:
          copyback: false
          prepare: |
            pkg install \
              build-essential \
              pkg-config
            curl -O https://pkgsrc.smartos.org/packages/SmartOS/bootstrap/bootstrap-trunk-x86_64-20240116.tar.gz
            tar -zxpf bootstrap-trunk-x86_64-20240116.tar.gz -C /
            export PATH=/opt/local/sbin:/opt/local/bin:/usr/gnu/bin:/usr/bin:/usr/sbin:/sbin:$PATH
            pkgin -y install \
              avahi \
              gnome-tracker \
              libevent \
              libgcrypt \
              meson \
              talloc
          run: |
            export PATH=/opt/local/sbin:/opt/local/bin:/usr/gnu/bin:/usr/bin:/usr/sbin:/sbin:$PATH
            meson setup build \
              -Dwith-bdb=/opt/local \
              -Dwith-libgcrypt-dir=/opt/local \
              -Dwith-tracker-pkgconfig-version=3.0 \
              -Dpkg_config_path=/opt/local/lib/pkgconfig
            ninja -C build

  build-freebsd:
    name: "FreeBSD"
    runs-on: ubuntu-22.04
    permissions:
      contents: read
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v4
      - name: "Build on VM"
        uses: vmactions/freebsd-vm@v1.0.6
        with:
          copyback: false
          prepare: |
            pkg install -y \
              meson \
              avahi \
              bison \
              db5 \
              flex \
              libevent \
              libgcrypt \
              libressl \
              perl5 \
              pkgconf \
              talloc \
              tracker3
          run: |
            meson setup build
              -Dwith-ssl-dir=/usr/local \
              -Dwith-tracker-pkgconfig-version=3.0 \
              -Dpkg_config_path=/usr/local/libdata/pkgconfig \
              -Dbuild-tests=true
            ninja -C build
            cd build && meson test

  build-openbsd:
    name: "OpenBSD"
    runs-on: ubuntu-22.04
    permissions:
      contents: read
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v4
      - name: "Build on VM"
        uses: vmactions/openbsd-vm@v1.0.7
        with:
          copyback: false
          prepare: |
            pkg_add -I \
              meson \
              avahi \
              bison \
              dbus-glib \
              db-4.6.21p7v0 \
              flex \
              gcc-11.2.0p9 \
              openldap-client-2.6.6v0 \
              pkgconf \
              libevent \
              libgcrypt \
              libtalloc \
              tracker3 \
          run: |
            meson setup build
              -Dwith-tracker-pkgconfig-version=3.0 \
              -Dpkg_config_path=/usr/local/lib/pkgconfig \
              -Dbuild-tests=true
            ninja -C build
            cd build && meson test

  build-netbsd:
    name: "NetBSD"
    runs-on: ubuntu-22.04
    permissions:
      contents: read
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v4
      - name: "Build on VM"
        uses: vmactions/netbsd-vm@v1.0.5
        with:
          copyback: false
          prepare: |
            pkg_add \
              meson \
              avahi \
              bison \
              db5 \
              dbus-glib \
              gcc13 \
              gnome-tracker \
              libevent \
              libgcrypt \
              libressl \
              openldap \
              perl \
              pkg-config \
              talloc
          run: |
            meson setup build \
              -Dwith-tracker-pkgconfig-version=3.0 \
              -Dpkg_config_path=/usr/pkg/lib/pkgconfig
            ninja -C build

  build-dflybsd:
    name: "DragonflyBSD"
    runs-on: ubuntu-22.04
    permissions:
      contents: read
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v4
      - name: "Build on VM"
        uses: vmactions/dragonflybsd-vm@v1
        with:
          copyback: false
          prepare: |
            pkg install -y \
              avahi \
              db5 \
              gmake \
              libevent \
              libgcrypt \
              meson \
              perl5 \
              pkgconf \
              py39-gdbm \
              py39-sqlite3 \
              py39-tkinter \
              talloc \
              tracker3
          run: |
            meson setup build \
              -Dwith-ssl-dir=/usr/local \
              -Dwith-tracker-pkgconfig-version=3.0 \

  build-solaris:
    if: false
    name: "Solaris"
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v4
      - name: "Build on VM"
        uses: vmactions/solaris-vm@v1.0.2
        with:
          copyback: false
          prepare: |
            pip install meson
            pkg install \
              gcc \
              libevent \
              libgcrypt \
              pkg-config
          run: |
            meson setup build \
              -Dwith-afpstats=disabled \
              -Dpkg_config_path=/usr/lib/64/pkgconfig \
              -Dbuild_tests=true
            ninja -C build
            cd build && meson test

  static_analysis:
    name: Static Analysis
    runs-on: ubuntu-22.04
    env:
      # Directory where build-wrapper output will be placed
      BUILD_WRAPPER_OUT_DIR: build_wrapper_output_directory
    if: ${{ !github.event.pull_request.head.repo.fork }} # Run only if not originating from a fork
    steps:
      - uses: actions/checkout@v4
        with:
          # Shallow clones should be disabled for a better relevancy of analysis
          fetch-depth: 0
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install --assume-yes --no-install-recommends ${{ env.APT_PACKAGES }}
      - name: Install sonar-scanner and build-wrapper
        uses: SonarSource/sonarcloud-github-c-cpp@v2
      - name: Run build-wrapper
        run: |
          mkdir -p ${{ env.BUILD_WRAPPER_OUT_DIR }}
          ./bootstrap
          ./configure \
            --enable-krbV-uam \
            --enable-pgp-uam \
            --with-tracker-pkgconfig-version=3.0
          build-wrapper-linux-x86-64 --out-dir ${{ env.BUILD_WRAPPER_OUT_DIR }} make -j $(nproc) all
      - name: Run sonar-scanner
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          sonar-scanner --define sonar.cfamily.build-wrapper-output="${{ env.BUILD_WRAPPER_OUT_DIR }}"
